### ISSUE TITLE
Нерабочая технология "i18n-lang-js-chunks"

### ISSUE THREAD

**Issue by markelog** [enb-make/enb-bembundle#16]
Сейчас технологию `i18n-lang-js-chunks` использовать нельзя, из-за неверных путей вроде таких -

https://github.com/enb-make/enb-bembundle/blob/5e310bb6cf3aa59dda3e98c890df584da6c88563/techs/i18n-lang-js-chunks.js#L26

**Comment by blond** [comment]
Привет! 

Пришлёшь PR с исправлениями?

**Comment by markelog** [comment]
Ага, закончу обновляться, выпустишь новую версию сразу после?

**Comment by blond** [comment]
Да, конечно.
